Make sharness a tool

diff --git a/sharness b/sharness
--- a/sharness
+++ b/sharness
@@ -21,6 +21,8 @@
 export SHARNESS_VERSION="0.2.2"
 export SHARNESS_TEST_EXTENSION="t"
 
+export HARNESS_ACTIVE=1
+
 ORIGINAL_TERM=$TERM
 
 # For repeatability, reset the environment to a known state.
@@ -72,7 +74,8 @@ while test "$#" -ne 0; do
 		root=$(expr "z$1" : 'z[^=]*=\(.*\)')
 		shift ;;
 	*)
-		echo "error: unknown test option '$1'" >&2; exit 1 ;;
+        break ;;
+		#echo "error: unknown test option '$1'" >&2; exit 1 ;;
 	esac
 done
 
@@ -112,7 +115,7 @@ say() {
 	say_color info "$*"
 }
 
-test -n "$test_description" || error "Test script did not set test_description."
+#test -n "$test_description" || error "Test script did not set test_description."
 
 if test "$help" = "t"; then
 	echo "$test_description"
@@ -570,7 +573,7 @@ test_done() {
 	if test -z "$HARNESS_ACTIVE"; then
 		test_results_dir="$TEST_DIRECTORY/test-results"
 		mkdir -p "$test_results_dir"
-		test_results_path="$test_results_dir/${0%.$SHARNESS_TEST_EXTENSION}.$$.counts"
+		test_results_path="$test_results_dir/${testfile%.$SHARNESS_TEST_EXTENSION}.$$.counts"
 
 		cat >>"$test_results_path" <<-EOF
 		total $test_count
@@ -624,35 +627,43 @@ else
 fi
 export PATH
 
-# Prepare test area.
-test_dir="trash directory.$(basename "$0" .sh)"
-test -n "$root" && test_dir="$root/$test_dir"
-case "$test_dir" in
-/*) TRASH_DIRECTORY="$test_dir" ;;
- *) TRASH_DIRECTORY="$TEST_DIRECTORY/$test_dir" ;;
-esac
-test "$debug" = "t" || remove_trash="$TRASH_DIRECTORY"
-rm -rf "$test_dir" || {
-	EXIT_OK=t
-	echo >&5 "FATAL: Cannot prepare test area"
-	exit 1
-}
+for f; do
+    (
+    testfile="$TEST_DIRECTORY/$f"
+    # Prepare test area.
+    test_dir="trash directory.$(basename "$testfile" .t)"
+    test -n "$root" && test_dir="$root/$test_dir"
+    case "$test_dir" in
+    /*) TRASH_DIRECTORY="$test_dir" ;;
+     *) TRASH_DIRECTORY="$TEST_DIRECTORY/$test_dir" ;;
+    esac
+    test "$debug" = "t" || remove_trash="$TRASH_DIRECTORY"
+    rm -rf "$test_dir" || {
+        EXIT_OK=t
+        echo >&5 "FATAL: Cannot prepare test area"
+        exit 1
+    }
 
-HOME="$TRASH_DIRECTORY"
-export HOME
+    HOME="$TRASH_DIRECTORY"
+    export HOME
 
-mkdir -p "$test_dir" || exit 1
-# Use -P to resolve symlinks in our working directory so that the cwd
-# in subprocesses like git equals our $PWD (for pathname comparisons).
-cd -P "$test_dir" || exit 1
+    mkdir -p "$test_dir" || exit 1
+    # Use -P to resolve symlinks in our working directory so that the cwd
+    # in subprocesses like git equals our $PWD (for pathname comparisons).
+    cd -P "$test_dir" || exit 1
 
-this_test=${0##*/}
-this_test=${this_test%.$SHARNESS_TEST_EXTENSION}
-for skp in $SKIP_TESTS; do
-	case "$this_test" in
-	$skp)
-		say_color skip >&3 "skipping test $this_test altogether"
-		skip_all="skip all tests in $this_test"
-		test_done
-	esac
+    this_test=${testfile##*/}
+    this_test=${this_test%.$SHARNESS_TEST_EXTENSION}
+    for skp in $SKIP_TESTS; do
+        case "$this_test" in
+        $skp)
+            say_color skip >&3 "skipping test $this_test altogether"
+            skip_all="skip all tests in $this_test"
+            test_done
+        esac
+    done
+
+    . "$testfile"
+    test_done
+    )
 done
